accent = "#ffffff"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#0078d7"
selection_foreground = "#ffffff"
selection_background = "#005a9e"

color0 = "#005a9e"
color1 = "#ffffff"
color2 = "#d9ecff"
color3 = "#88c3ff"
color4 = "#0037da"
color5 = "#ffffff"
color6 = "#d9ecff"
color7 = "#ffffff"
color8 = "#0037da"
color9 = "#ffffff"
color10 = "#d9ecff"
color11 = "#88c3ff"
color12 = "#329aef"
color13 = "#ffffff"
color14 = "#d9ecff"
color15 = "#ffffff"
