$activeBorderColor = rgba(ffffffff)
$inactiveBorderColor = rgba(d9ecffee)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
