set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=#0078d7,bg=#ffffff,bold] #S #[bg=default] "
set -g status-right "#[fg=#0078d7]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#d9d9d9]#h "
set -g window-status-format "#[fg=#d9d9d9] #I:#W "
set -g window-status-current-format "#[fg=#0078d7,bold] #I:#W "
set -g pane-border-style "fg=#d9d9d9"
set -g pane-active-border-style "fg=#0078d7"
set -g message-style "bg=#ffffff,fg=#0078d7"
set -g message-command-style "bg=#ffffff,fg=#0078d7"
set -g mode-style "bg=#ffffff,fg=#0078d7"
set -g popup-style "bg=#ffffff,fg=#0078d7"
set -g popup-border-style "bg=#ffffff,fg=#0078d7"
set -g menu-style "bg=#ffffff,fg=#0078d7"
set -g menu-selected-style "bg=#0078d7,fg=#ffffff"
setw -g clock-mode-colour "#0078d7"
